переименовует тег на footer
AleksanrKotlyar/project-icecream pull request #49
Opened 2022-06-29 17:49 UTC by turus090

2022-06-29 18:13 UTC, AleksanrKotlyar requested changes

2022-06-29 18:13 UTC, AleksanrKotlyar commented on src/partials/footer.html
>              <div>
убери, в нем нет смысла

2022-06-29 18:13 UTC, AleksanrKotlyar commented on src/partials/footer.html
>              <div class="footer-contacts">
убери, нет надобности

2022-06-29 18:13 UTC, AleksanrKotlyar commented on src/partials/footer.html
>                  <p class="footer-contacts__text">Feel free to contact </p>
как сказала Алена - это часть контактов, помести в тэг address

2022-06-29 22:12 UTC, turus090 commented on src/partials/footer.html
>              <div class="footer-contacts">
убрал

2022-06-30 04:50 UTC, AleksanrKotlyar requested changes
Исправить + подгрузить ветку footer.html со всеми исправлениями(убрать лишний див div class="footer-contect container">)

2022-06-30 04:50 UTC, AleksanrKotlyar commented on src/sass/components/footer/_footer.scss
>              line-height: 22.32px;
исправить как нас учили, в относительные ед. или %  или множитель

2022-06-30 04:50 UTC, AleksanrKotlyar commented on src/sass/components/footer/_footer.scss
>              line-height: 21px;
исправить как нас учили, в относительные ед. или %  или множитель

2022-06-30 04:50 UTC, AleksanrKotlyar commented on src/sass/components/footer/_footer.scss
>              line-height: 21px;
исправить как нас учили, в относительные ед. или %  или множитель

2022-06-30 04:50 UTC, AleksanrKotlyar commented on src/sass/components/footer/_footer.scss
>                  line-height: 26px;
исправить как нас учили, в относительные ед. или %  или множитель

2022-06-30 12:11 UTC, AleksanrKotlyar approved these changes

2022-06-30 12:11 UTC, merged