feature/contacts
AleksanrKotlyar/project-icecream pull request #9
Opened 2022-06-24 17:11 UTC by Shundrik

ничего не менял

2022-06-24 17:28 UTC, AleksanrKotlyar requested changes

2022-06-24 17:28 UTC, AleksanrKotlyar commented on src/partials/contacts.html
> +          <ul class="contact-card__list">
ГИДЭ list

2022-06-25 17:55 UTC, AleksanrKotlyar requested changes

2022-06-25 17:55 UTC, AleksanrKotlyar commented on src/partials/contacts.html
> +<!DOCTYPE html>
Проверь валидатором код и убери плз все лишнее :<!DOCTYPE html>, head, body

2022-06-25 20:13 UTC, Shundrik commented on src/partials/contacts.html
> +<!DOCTYPE html>
Cаша, проверил. Ниже модального окна можно не проверять оно не готово.

2022-06-26 08:43 UTC, AleksanrKotlyar requested changes
В принципе семантически и чистоты кода все в порядке, бегло посмотрел единственное что есть предложения, если не захочешь исправлять напиши в комментах, я закрою осуждения и смерджу в мэйн ветку, так как эти пожелания не критичны, молодец у тебя самая объемная секция получилась на тек. момент

2022-06-26 08:43 UTC, AleksanrKotlyar commented on src/partials/contacts.html
> +            href="mailto:"
может добавить noreply@envato.co везде просто для наглядности?

2022-06-26 08:43 UTC, AleksanrKotlyar commented on src/sass/components/contacts/_contacts.scss
> +  color: #ffffff;
можно использовать переменные

2022-06-26 08:43 UTC, AleksanrKotlyar commented on src/sass/components/contacts/_contacts.scss
> +.green {
не критично, чего не использовал как модификатор если по ВЭМ

2022-06-26 08:55 UTC, Shundrik commented on src/sass/components/contacts/_contacts.scss
> +.green {
конечно, раз договорились исправил!

2022-06-26 08:55 UTC, Shundrik commented on src/sass/components/contacts/_contacts.scss
> +  color: #ffffff;
правильно , заменил!

2022-06-26 08:55 UTC, Shundrik commented on src/partials/contacts.html
> +            href="mailto:"
отличное замечание добавил.

2022-06-26 08:56 UTC, Shundrik commented on src/index.html
> +  <body class="modal-open">
Да, 100% спасибо, исправил!

2022-06-26 09:15 UTC, AleksanrKotlyar submitted a review, later dismissed

2022-06-26 10:32 UTC, AleksanrKotlyar approved these changes

2022-06-26 10:33 UTC, merged